version: "3"
services:
  redis: 
    image: redis:latest
    ports:
    - "${REDIS_PORT}:6379"
    volumes: 
      - /redis${RUN_TYPE}:/data
    container_name: redis${RUN_TYPE}
  app:
    build: .
    depends_on: 
      - redis
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - ENVIRONMENT=${ENV_TYPE}
      - HOST=localhost
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=0
    container_name: App${RUN_TYPE}