version: "3"
services:
  - redis: 
      image: redis:latest
      ports:
      - "6379:6379"
  - app:
      build: .
      depends_on: 
        - redis
      ports: 
        - "8000:8000"
      environment:
        - ENVIRONMENT=DEV
        - HOST=localhost
        - PORT=8000
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0